## Лабораторная работа №1: NumPy
--------
Шаина М.М. 
6132-010402D

### 1. Описание втроенных функций numpy

In [1]:
#Импортируем необходимые библиотеки 

import numpy as np
import pandas as pd

import datetime as dt

#### 1.1 Cоздание массива 

1) Создадим массив нулей. Первым параметром передадим кол-во строк, вторым - кол-во столбцов.

In [2]:
#Создадим 2D numpy массив из нулей
arr = np.zeros((3, 7), np.int32) 
arr

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)

2) Создадим массив со случайными элементами, используя функцию sample

In [3]:
#Возвращает массив случайных чисел с размерами, указанными в кортеже (все числа - из промежутка [0, 1)).
np.random.sample((2, 3))

array([[0.1427039 , 0.60436401, 0.4694004 ],
       [0.99475485, 0.02903167, 0.83309631]])

3) Сгенерируем массив случайных чисел из равномерного распределения, 
   который можно получить с помощь функции uniform.

In [4]:
a = np.random.uniform(2, 8, (2, 10))
a

array([[2.07471145, 2.8566868 , 2.83707513, 5.72275148, 5.5725215 ,
        3.08040081, 7.50763325, 2.59885887, 5.59950196, 4.45458775],
       [3.92500628, 5.34038371, 3.80769062, 3.34188046, 3.89037243,
        6.51040524, 3.8526468 , 4.86202395, 2.32550547, 2.44999762]])

#### 1.2 Вывод информации о массиве

In [5]:
#Размерность массива
a.shape

(2, 10)

In [6]:
#Тип данных массива
a.dtype

dtype('float64')

#### 1.3 Подмножества, срезы, индексация

In [7]:
a = np.array([[1, 93, 9, 0], 
              [2, 6, 7, 9], 
              [4, 6, 9, 10], 
              [3, 34, 15, 6]])
a

array([[ 1, 93,  9,  0],
       [ 2,  6,  7,  9],
       [ 4,  6,  9, 10],
       [ 3, 34, 15,  6]])

In [8]:
#1)Выводим первую строки и все столбцы. 2)Выводим первую строку. Результат одинаковый
a[ 0, : ], a[ 0 ]

(array([ 1, 93,  9,  0]), array([ 1, 93,  9,  0]))

In [9]:
# Получим срез массива из первых трех строк и двух столбцов (со второго по третий, т.к. индексация начинается с 0)
a[ 0:3, 1:3 ]

array([[93,  9],
       [ 6,  7],
       [ 6,  9]])

In [10]:
a[ ::-1 ] # Reversed array

array([[ 3, 34, 15,  6],
       [ 4,  6,  9, 10],
       [ 2,  6,  7,  9],
       [ 1, 93,  9,  0]])

#### 1.4 Манипуляции с матрицами

In [11]:
#Добавить элементы в массив можно с помощью метода append
np.append( [[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0 )

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#Вставить значения в массив
a1 = np.insert(a, [4], [[0],[12],[3],[14]], axis=1)
a1

array([[ 1, 93,  9,  0,  0],
       [ 2,  6,  7,  9, 12],
       [ 4,  6,  9, 10,  3],
       [ 3, 34, 15,  6, 14]])

In [13]:
#Найти максимальное и минимальное число массива
min = np.amin(a1)
max = np.amax(a1)
print(f"минимальное значение: {min}, максимальное значение: {max}")

минимальное значение: 0, максимальное значение: 93


In [14]:
#Транспорнирование матрицы 
a1.T #  np.transpose( a1 )

array([[ 1,  2,  4,  3],
       [93,  6,  6, 34],
       [ 9,  7,  9, 15],
       [ 0,  9, 10,  6],
       [ 0, 12,  3, 14]])

In [15]:
a1 = np.delete(a1, np.s_[::2], 1) 
a1

array([[93,  0],
       [ 6,  9],
       [ 6, 10],
       [34,  6]])

In [16]:
a1.ravel() # a1 ссылается на одномерное представление массива

array([93,  0,  6,  9,  6, 10, 34,  6])

#### 1.5 Инициализация генератора случайных чисел

seed(число) - инициализация генератора.

In [17]:
np.random.seed(1000)
np.random.random(10)

array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454,
       0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072])

#### 1.6 Линейная алгебра 

In [18]:
# Matrix product of two arrays.
a = np.random.randint(138, 456,(4,4))
b = np.random.randint(62, 89,(4,5))
d = a@b
d

array([[117176, 114268, 124730, 125594, 101600],
       [115253, 111694, 122610, 123510, 100269],
       [102440,  98560, 108645, 109831,  89220],
       [ 80636,  80632,  88083,  88759,  73400]])

In [19]:
# Matmul for N-dim >= 2 matrix
a = np.random.randint(138, 456,(4,4,4))
b = np.random.randint(62, 89,(4,4,4))

np.dot(a,b)[:,:,-1]

array([[[ 63403,  64359,  67507,  64256],
        [ 68298,  78271,  79604,  68935],
        [ 51094,  54737,  57246,  52160],
        [ 70818,  77287,  78694,  71166]],

       [[ 85423,  96430,  98911,  86788],
        [ 62442,  67040,  68832,  62479],
        [ 74677,  84127,  86581,  76294],
        [ 78250,  87249,  89644,  79457]],

       [[ 74424,  75076,  79178,  75607],
        [ 60083,  62172,  64965,  60971],
        [ 73323,  79617,  81179,  73910],
        [ 89804, 101152, 103658,  91617]],

       [[ 84200,  86127,  89656,  84792],
        [ 92473,  97929, 101563,  94235],
        [ 96377,  99362, 103263,  97887],
        [ 91480,  92473,  96846,  91989]]])

In [20]:
# Return the sum along diagonals of the array

a = np.arange(24).reshape((2,2,2,3))
np.trace(a).shape

(2, 3)

### 2. OLAP-куб

In [21]:
# Генерация OLAP-куба

product_group_id = np.arange(0, 54)
date = np.arange(dt.date(2023, 1, 2), dt.date(2023, 1, 31)) # Продажи за месяц (со 2-го по 31-е января)
date = np.append(date, dt.date(2023, 1, 31)).astype(str)
store_id = np.arange(0, 3)

product_group_ratio = (np.random.rand(54) + 0.1)/1.1
store_id_ratio = (np.random.rand(3) + 0.5)/1.5

cube = np.zeros([product_group_id.size, store_id.size, date.size])

for p in range(product_group_id.size):
  for s in range(store_id.size):
    for d in range(date.size):
      rez = np.random.rand()*product_group_ratio[p]*store_id_ratio[s]*100
      cube[p][s][d] = rez if rez > 0.1 else 0

#print(cube)

### 3. Агрегатные функции для OLAP-куба

In [22]:
print("\nМагазин с максимальными продажами на конец месяца:")
srote_1, store_2, store_3 = np.sum(cube[:,0,:]), np.sum(cube[:,1,:]), np.sum(cube[:,2,:])
a = np.array([srote_1, store_2, store_3])
print(np.amax(a))

print("\nСумма продаж всех товаров во всех магазинах за весь месяц:")
print(np.sum(cube[:, :, :]))

print("\nСумма продаж по дням первой недели для товаров группы 3 во всех магазинах:")
print(np.sum(cube[3:4, :, 0:7], axis = (0, 1)))

print("\nСредние продажи группы товаров за весь месяц по каждому магазину:")
print(np.mean(cube[:, :, :], axis = (0, 2)))

print("\nМинимальные продажи по группам товаров во всех магазинах за первые 2 недели:")
print(np.min(cube[:, :, 0:14], axis = (1, 2)))

print("\nМаксимальные продажи по 3 группам товаров по магазинам:")
print(np.max(cube[0:3, :, :], axis = 2))


Магазин с максимальными продажами на конец месяца:
39272.751423393536

Сумма продаж всех товаров во всех магазинах за весь месяц:
81820.21439931219

Сумма продаж по дням первой недели для товаров группы 3 во всех магазинах:
[27.92221487 34.27661757 38.53218885 15.40211099 37.09205615 45.84644231
 15.31991536]

Средние продажи группы товаров за весь месяц по каждому магазину:
[15.71099339 24.24243915 10.55287265]

Минимальные продажи по группам товаров во всех магазинах за первые 2 недели:
[0.10886382 0.14740837 0.91302444 0.77660831 0.86523356 0.
 1.16116998 0.28943306 0.         0.         0.88606961 0.
 0.27796449 0.36617389 0.5119882  0.15187648 0.91778725 0.49416603
 0.57100961 0.64851203 0.29256574 0.14240651 0.16415579 0.6805482
 0.89274523 0.20353419 2.41526477 0.36302226 3.12284073 0.54331984
 3.97002784 0.16949636 0.10988099 0.31907488 1.84566189 0.9965798
 0.65649541 3.83965611 1.31981503 0.         0.79758514 0.
 2.12827293 0.51778847 0.54649566 0.16697323 0.         0.5745